/*
* generated by Xtext
*/
package ch.vorburger.el.ui.contentassist;

import ch.vorburger.el.ui.contentassist.AbstractELProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ELProposalProvider extends AbstractELProposalProvider {

}
