/*
* generated by Xtext
*/
package ch.vorburger.el.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.eclipse.xtext.xbase.XExpression;
import org.eclipse.xtext.xbase.XIfExpression;
import org.eclipse.xtext.xbase.XMemberFeatureCall;
import org.eclipse.xtext.xbase.XStringLiteral;

import ch.vorburger.el.eL.DecimalLiteral;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
@SuppressWarnings("restriction")
public class ELLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public ELLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	public String text(XStringLiteral literal) {
		return literal.getValue();
	}

	public String text(DecimalLiteral literal) {
		return literal.getValue();
	}
	
	public String text(XExpression expr) {
		return expr.toString();
	}
	
	public String text(XIfExpression expr) {
		return "IF";
	}
	
	public String text(XMemberFeatureCall call) {
		return call.getMemberCallTarget().toString();
	}

}
