/*
* generated by Xtext
*/
package ch.vorburger.elang.ui.contentassist;

import ch.vorburger.elang.ui.contentassist.AbstractELangDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ELangDslProposalProvider extends AbstractELangDslProposalProvider {

}
