/*
 * generated by Xtext
 */
package ch.vorburger.elang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ELangDslUiModule extends ch.vorburger.elang.ui.AbstractELangDslUiModule {
	public ELangDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
