/*
 * generated by Xtext
 */
package ch.vorburger.el.scoping;

import org.eclipse.xtext.xbase.scoping.XbaseScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class ELScopeProvider extends XbaseScopeProvider {

}
