/*
 * generated by Xtext
 */
package ch.vorburger.el.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ELExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ch.vorburger.el.ui.internal.ELActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ch.vorburger.el.ui.internal.ELActivator.getInstance().getInjector("ch.vorburger.el.EL");
	}
	
}
