/*
* generated by Xtext
*/
package ch.vorburger.el;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ELUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ch.vorburger.el.ui.internal.ELActivator.getInstance().getInjector("ch.vorburger.el.EL");
	}
	
}
