/*
 * generated by Xtext
 */
package ch.vorburger.elang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ELangDslRuntimeModule extends ch.vorburger.elang.AbstractELangDslRuntimeModule {

}
