/*
 * generated by Xtext
 */
package ch.vorburger.el.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;

import ch.vorburger.el.typing.ELJvmTypeProviderFactory;
import ch.vorburger.el.ui.hovering.ELEObjectDocumentationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
@SuppressWarnings("restriction")
public class ELUiModule extends ch.vorburger.el.ui.AbstractELUiModule {
	public ELUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends org.eclipse.xtext.common.types.access.IJvmTypeProvider.Factory> bindIJvmTypeProvider$Factory() {
		return ELJvmTypeProviderFactory.class;
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
		return ELEObjectDocumentationProvider.class;
	}

}
