/*
 * generated by Xtext
 */
package ch.vorburger.el.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.common.types.xtext.ui.ITypesProposalProvider;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;

import ch.vorburger.el.ui.contentassist.ELTypeProposalProvider;
import ch.vorburger.el.ui.hovering.ELEObjectDocumentationProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ELUiModule extends ch.vorburger.el.ui.AbstractELUiModule {
	public ELUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
		return ELEObjectDocumentationProvider.class;
	}

	@Override
	public Class<? extends ITypesProposalProvider> bindITypesProposalProvider() {
		return ELTypeProposalProvider.class;
	}
}
